//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
//using System.Data.EntityClient;
//using System.Data.Objects;
//using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Recompensapp01
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class DatabaseEntitiesAlumnos : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto DatabaseEntitiesAlumnos usando la cadena de conexión encontrada en la sección 'DatabaseEntitiesAlumnos' del archivo de configuración de la aplicación.
        /// </summary>
        public DatabaseEntitiesAlumnos() : base("name=DatabaseEntitiesAlumnos", "DatabaseEntitiesAlumnos")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto DatabaseEntitiesAlumnos.
        /// </summary>
        public DatabaseEntitiesAlumnos(string connectionString) : base(connectionString, "DatabaseEntitiesAlumnos")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto DatabaseEntitiesAlumnos.
        /// </summary>
        public DatabaseEntitiesAlumnos(EntityConnection connection) : base(connection, "DatabaseEntitiesAlumnos")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Alumno> Alumno
        {
            get
            {
                if ((_Alumno == null))
                {
                    _Alumno = base.CreateObjectSet<Alumno>("Alumno");
                }
                return _Alumno;
            }
        }
        private ObjectSet<Alumno> _Alumno;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Obtencion> Obtencion
        {
            get
            {
                if ((_Obtencion == null))
                {
                    _Obtencion = base.CreateObjectSet<Obtencion>("Obtencion");
                }
                return _Obtencion;
            }
        }
        private ObjectSet<Obtencion> _Obtencion;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Profesor> Profesor
        {
            get
            {
                if ((_Profesor == null))
                {
                    _Profesor = base.CreateObjectSet<Profesor>("Profesor");
                }
                return _Profesor;
            }
        }
        private ObjectSet<Profesor> _Profesor;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Ventaja> Ventaja
        {
            get
            {
                if ((_Ventaja == null))
                {
                    _Ventaja = base.CreateObjectSet<Ventaja>("Ventaja");
                }
                return _Ventaja;
            }
        }
        private ObjectSet<Ventaja> _Ventaja;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Alumno. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAlumno(Alumno alumno)
        {
            base.AddObject("Alumno", alumno);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Obtencion. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToObtencion(Obtencion obtencion)
        {
            base.AddObject("Obtencion", obtencion);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Profesor. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToProfesor(Profesor profesor)
        {
            base.AddObject("Profesor", profesor);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Ventaja. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToVentaja(Ventaja ventaja)
        {
            base.AddObject("Ventaja", ventaja);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Alumno")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Alumno : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Alumno.
        /// </summary>
        /// <param name="nia">Valor inicial de la propiedad Nia.</param>
        public static Alumno CreateAlumno(global::System.String nia)
        {
            Alumno alumno = new Alumno();
            alumno.Nia = nia;
            return alumno;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nia
        {
            get
            {
                return _Nia;
            }
            set
            {
                if (_Nia != value)
                {
                    OnNiaChanging(value);
                    ReportPropertyChanging("Nia");
                    _Nia = StructuralObject.SetValidValue(value, false, "Nia");
                    ReportPropertyChanged("Nia");
                    OnNiaChanged();
                }
            }
        }
        private global::System.String _Nia;
        partial void OnNiaChanging(global::System.String value);
        partial void OnNiaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre_alumno
        {
            get
            {
                return _Nombre_alumno;
            }
            set
            {
                OnNombre_alumnoChanging(value);
                ReportPropertyChanging("Nombre_alumno");
                _Nombre_alumno = StructuralObject.SetValidValue(value, true, "Nombre_alumno");
                ReportPropertyChanged("Nombre_alumno");
                OnNombre_alumnoChanged();
            }
        }
        private global::System.String _Nombre_alumno;
        partial void OnNombre_alumnoChanging(global::System.String value);
        partial void OnNombre_alumnoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Apellidos_alumno
        {
            get
            {
                return _Apellidos_alumno;
            }
            set
            {
                OnApellidos_alumnoChanging(value);
                ReportPropertyChanging("Apellidos_alumno");
                _Apellidos_alumno = StructuralObject.SetValidValue(value, true, "Apellidos_alumno");
                ReportPropertyChanged("Apellidos_alumno");
                OnApellidos_alumnoChanged();
            }
        }
        private global::System.String _Apellidos_alumno;
        partial void OnApellidos_alumnoChanging(global::System.String value);
        partial void OnApellidos_alumnoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Curso
        {
            get
            {
                return _Curso;
            }
            set
            {
                OnCursoChanging(value);
                ReportPropertyChanging("Curso");
                _Curso = StructuralObject.SetValidValue(value, true, "Curso");
                ReportPropertyChanged("Curso");
                OnCursoChanged();
            }
        }
        private global::System.String _Curso;
        partial void OnCursoChanging(global::System.String value);
        partial void OnCursoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Grupo
        {
            get
            {
                return _Grupo;
            }
            set
            {
                OnGrupoChanging(value);
                ReportPropertyChanging("Grupo");
                _Grupo = StructuralObject.SetValidValue(value, true, "Grupo");
                ReportPropertyChanged("Grupo");
                OnGrupoChanged();
            }
        }
        private global::System.String _Grupo;
        partial void OnGrupoChanging(global::System.String value);
        partial void OnGrupoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Saldo
        {
            get
            {
                return _Saldo;
            }
            set
            {
                OnSaldoChanging(value);
                ReportPropertyChanging("Saldo");
                _Saldo = StructuralObject.SetValidValue(value, "Saldo");
                ReportPropertyChanged("Saldo");
                OnSaldoChanged();
            }
        }
        private Nullable<global::System.Int32> _Saldo;
        partial void OnSaldoChanging(Nullable<global::System.Int32> value);
        partial void OnSaldoChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Obtencion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Obtencion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Obtencion.
        /// </summary>
        /// <param name="idObtencion">Valor inicial de la propiedad idObtencion.</param>
        public static Obtencion CreateObtencion(global::System.Int32 idObtencion)
        {
            Obtencion obtencion = new Obtencion();
            obtencion.idObtencion = idObtencion;
            return obtencion;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idObtencion
        {
            get
            {
                return _idObtencion;
            }
            set
            {
                if (_idObtencion != value)
                {
                    OnidObtencionChanging(value);
                    ReportPropertyChanging("idObtencion");
                    _idObtencion = StructuralObject.SetValidValue(value, "idObtencion");
                    ReportPropertyChanged("idObtencion");
                    OnidObtencionChanged();
                }
            }
        }
        private global::System.Int32 _idObtencion;
        partial void OnidObtencionChanging(global::System.Int32 value);
        partial void OnidObtencionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String niaAlumno
        {
            get
            {
                return _niaAlumno;
            }
            set
            {
                OnniaAlumnoChanging(value);
                ReportPropertyChanging("niaAlumno");
                _niaAlumno = StructuralObject.SetValidValue(value, true, "niaAlumno");
                ReportPropertyChanged("niaAlumno");
                OnniaAlumnoChanged();
            }
        }
        private global::System.String _niaAlumno;
        partial void OnniaAlumnoChanging(global::System.String value);
        partial void OnniaAlumnoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idrVentaja
        {
            get
            {
                return _idrVentaja;
            }
            set
            {
                OnidrVentajaChanging(value);
                ReportPropertyChanging("idrVentaja");
                _idrVentaja = StructuralObject.SetValidValue(value, "idrVentaja");
                ReportPropertyChanged("idrVentaja");
                OnidrVentajaChanged();
            }
        }
        private Nullable<global::System.Int32> _idrVentaja;
        partial void OnidrVentajaChanging(Nullable<global::System.Int32> value);
        partial void OnidrVentajaChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Profesor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Profesor : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Profesor.
        /// </summary>
        /// <param name="dni">Valor inicial de la propiedad dni.</param>
        public static Profesor CreateProfesor(global::System.String dni)
        {
            Profesor profesor = new Profesor();
            profesor.dni = dni;
            return profesor;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String dni
        {
            get
            {
                return _dni;
            }
            set
            {
                if (_dni != value)
                {
                    OndniChanging(value);
                    ReportPropertyChanging("dni");
                    _dni = StructuralObject.SetValidValue(value, false, "dni");
                    ReportPropertyChanged("dni");
                    OndniChanged();
                }
            }
        }
        private global::System.String _dni;
        partial void OndniChanging(global::System.String value);
        partial void OndniChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usr
        {
            get
            {
                return _usr;
            }
            set
            {
                OnusrChanging(value);
                ReportPropertyChanging("usr");
                _usr = StructuralObject.SetValidValue(value, true, "usr");
                ReportPropertyChanged("usr");
                OnusrChanged();
            }
        }
        private global::System.String _usr;
        partial void OnusrChanging(global::System.String value);
        partial void OnusrChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String psw
        {
            get
            {
                return _psw;
            }
            set
            {
                OnpswChanging(value);
                ReportPropertyChanging("psw");
                _psw = StructuralObject.SetValidValue(value, true, "psw");
                ReportPropertyChanged("psw");
                OnpswChanged();
            }
        }
        private global::System.String _psw;
        partial void OnpswChanging(global::System.String value);
        partial void OnpswChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre_prof
        {
            get
            {
                return _nombre_prof;
            }
            set
            {
                Onnombre_profChanging(value);
                ReportPropertyChanging("nombre_prof");
                _nombre_prof = StructuralObject.SetValidValue(value, true, "nombre_prof");
                ReportPropertyChanged("nombre_prof");
                Onnombre_profChanged();
            }
        }
        private global::System.String _nombre_prof;
        partial void Onnombre_profChanging(global::System.String value);
        partial void Onnombre_profChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String apellido_prof
        {
            get
            {
                return _apellido_prof;
            }
            set
            {
                Onapellido_profChanging(value);
                ReportPropertyChanging("apellido_prof");
                _apellido_prof = StructuralObject.SetValidValue(value, true, "apellido_prof");
                ReportPropertyChanged("apellido_prof");
                Onapellido_profChanged();
            }
        }
        private global::System.String _apellido_prof;
        partial void Onapellido_profChanging(global::System.String value);
        partial void Onapellido_profChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rol
        {
            get
            {
                return _rol;
            }
            set
            {
                OnrolChanging(value);
                ReportPropertyChanging("rol");
                _rol = StructuralObject.SetValidValue(value, true, "rol");
                ReportPropertyChanged("rol");
                OnrolChanged();
            }
        }
        private global::System.String _rol;
        partial void OnrolChanging(global::System.String value);
        partial void OnrolChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Ventaja")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ventaja : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Ventaja.
        /// </summary>
        /// <param name="idVentaja">Valor inicial de la propiedad idVentaja.</param>
        public static Ventaja CreateVentaja(global::System.Int32 idVentaja)
        {
            Ventaja ventaja = new Ventaja();
            ventaja.idVentaja = idVentaja;
            return ventaja;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idVentaja
        {
            get
            {
                return _idVentaja;
            }
            set
            {
                if (_idVentaja != value)
                {
                    OnidVentajaChanging(value);
                    ReportPropertyChanging("idVentaja");
                    _idVentaja = StructuralObject.SetValidValue(value, "idVentaja");
                    ReportPropertyChanged("idVentaja");
                    OnidVentajaChanged();
                }
            }
        }
        private global::System.Int32 _idVentaja;
        partial void OnidVentajaChanging(global::System.Int32 value);
        partial void OnidVentajaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombreVentaja
        {
            get
            {
                return _nombreVentaja;
            }
            set
            {
                OnnombreVentajaChanging(value);
                ReportPropertyChanging("nombreVentaja");
                _nombreVentaja = StructuralObject.SetValidValue(value, true, "nombreVentaja");
                ReportPropertyChanged("nombreVentaja");
                OnnombreVentajaChanged();
            }
        }
        private global::System.String _nombreVentaja;
        partial void OnnombreVentajaChanging(global::System.String value);
        partial void OnnombreVentajaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Valor
        {
            get
            {
                return _Valor;
            }
            set
            {
                OnValorChanging(value);
                ReportPropertyChanging("Valor");
                _Valor = StructuralObject.SetValidValue(value, "Valor");
                ReportPropertyChanged("Valor");
                OnValorChanged();
            }
        }
        private Nullable<global::System.Int32> _Valor;
        partial void OnValorChanging(Nullable<global::System.Int32> value);
        partial void OnValorChanged();

        #endregion

    }

    #endregion

}
